{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{ include "cluster-autoscaler.labels" . | indent 4 }}
  name: {{ .Values.rbac.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.serviceAccount.name }}
    namespace: {{ .Values.Namespace }}
{{- end -}}
